services:
    benkle.autopreflight.requestlistener:
        class: Benkle\AutoPreflightBundle\Listener\RequestListener
        tags:
            - name: kernel.event_listener
              event: kernel.request
              priority: 9999

    benkle.autopreflight.responselistener:
        class: Benkle\AutoPreflightBundle\Listener\ResponseListener
        arguments:
            - @benkle.autopreflight.rms
        tags:
            - name: kernel.event_listener
              event: kernel.response
              priority: 9999

    benkle.autopreflight.rms:
        class: Benkle\AutoPreflightBundle\Service\RouteMethodService
        arguments:
            - @router
